//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketTracker.data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TicketTrackerEntities : DbContext
    {
        public TicketTrackerEntities()
            : base("name=TicketTrackerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TSTDepartment> TSTDepartments { get; set; }
        public virtual DbSet<TSTEmployee> TSTEmployees { get; set; }
        public virtual DbSet<TSTTicketNote> TSTTicketNotes { get; set; }
        public virtual DbSet<TSTTicket> TSTTickets { get; set; }
        public virtual DbSet<TSTTicketStatus> TSTTicketStatuses { get; set; }
    }
}
