//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketTracker.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSTEmployee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TSTEmployee()
        {
            this.TSTTicketNotes = new HashSet<TSTTicketNote>();
            this.TSTTickets = new HashSet<TSTTicket>();
            this.TSTTickets1 = new HashSet<TSTTicket>();
        }
    
        public int EmpID { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string zip { get; set; }
        public string phone1 { get; set; }
        public string phone2 { get; set; }
        public string Email { get; set; }
        public int DeptID { get; set; }
        public string Image { get; set; }
        public System.DateTime DOB { get; set; }
        public System.DateTime HireDate { get; set; }
        public Nullable<System.DateTime> SeparationDate { get; set; }
        public bool IsActive { get; set; }
        public string JobTitle { get; set; }
        public string Notes { get; set; }
        public string UserID { get; set; }
    
        public virtual TSTDepartment TSTDepartment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSTTicketNote> TSTTicketNotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSTTicket> TSTTickets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSTTicket> TSTTickets1 { get; set; }
        //public string ImageURL { get; set; }
    }
}
