//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketTracker.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSTTicket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TSTTicket()
        {
            this.TSTTicketNotes = new HashSet<TSTTicketNote>();
        }
    
        public int TicketID { get; set; }
        public int StatusID { get; set; }
        public System.DateTime SubmissionDate { get; set; }
        public int SubmittedByID { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
        public string TicketDesc { get; set; }
        public Nullable<int> AssignedTechID { get; set; }
    
        public virtual TSTEmployee TSTEmployee { get; set; }
        public virtual TSTEmployee TSTEmployee1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSTTicketNote> TSTTicketNotes { get; set; }
        public virtual TSTTicketStatus TSTTicketStatus { get; set; }
    }
}
