//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketTracker.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSTTicketNote
    {
        public int TicketNotesID { get; set; }
        public System.DateTime NotationDate { get; set; }
        public int TicketID { get; set; }
        public int EmpID { get; set; }
        public string Notation { get; set; }
    
        public virtual TSTEmployee TSTEmployee { get; set; }
        public virtual TSTTicket TSTTicket { get; set; }
    }
}
